services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finora-app
    ports:
      - "8000:8000"
    environment:
      APP_NAME: Finora
      APP_ENV: local
      APP_KEY: "base64:cicwMqd3A02evWhNoHY0ggKPPwpx3Pfh6D51GvuF3G"
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000

      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: finora
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

      QUEUE_CONNECTION: database

      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: ""
      MAIL_FROM_ADDRESS: finora@example.com
      MAIL_FROM_NAME: Finora
    depends_on:
      postgres:
        condition: service_healthy
      mailpit:
        condition: service_started
    command: >
      sh -c "php artisan migrate --force &&
             php artisan serve --host=0.0.0.0 --port=8000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finora-worker
    environment:
      APP_ENV: local
      APP_KEY: "base64:cicwMqd3A02evWhNoHY0ggKPPwpx3Pfh6D51GvuF3G"
      APP_DEBUG: "true"
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: finora
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      QUEUE_CONNECTION: database
      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_FROM_ADDRESS: finora@example.com
      MAIL_FROM_NAME: Finora
    depends_on:
      postgres:
        condition: service_healthy
      mailpit:
        condition: service_started
    command: php artisan queue:work --tries=3

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finora-scheduler
    environment:
      APP_ENV: local
      APP_KEY: "base64:cicwMqd3A02evWhNoHY0ggKPPwpx3Pfh6D51GvuF3G"
      APP_DEBUG: "true"
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: finora
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      QUEUE_CONNECTION: database
      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_FROM_ADDRESS: finora@example.com
      MAIL_FROM_NAME: Finora
    depends_on:
    postgres:
      condition: service_healthy
    app:
      condition: service_started
    command: php artisan schedule:work

  postgres:
    image: postgres:17
    container_name: finora-postgres
    environment:
      POSTGRES_DB: finora
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - finora-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d finora"]
      interval: 5s
      timeout: 5s
      retries: 10

  mailpit:
    image: axllent/mailpit:latest
    container_name: finora-mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  finora-postgres-data: